### ISSUE TITLE
finalisations for friday

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-chrome-sourcerer#2]
We will launch the Yemeni project on friday. before then the following needs to be completed:
- ~~removing doubles from photo database (in sink)~~ :: Moving this to `geotagx-sourcerer-sink` as this will has a dependency on implementing the `geotagx-sourcerer-sink` dashboard. Also it has no relation with the geotagx-chrome-sourcerer 
- ~~formatting of category list shown to user~~
- ~~remove winter shelter and somali drought from options shown to user~~
- ~~disable the plugin on google search results, the urls sent in will be google urls and the source wont be correct. We also want people to go and look at the page to make sure what they are sending is correct~~
- ~~add option to search for image using google reverse image when on geotagx~~ (Implemented reverse image search using TinyEye instead)

**Comment by elliec** [comment]
@spMohanty I get an error when reverse searching for images from geotag-x. It is not searching for the image url but some sort of internal Geotagx url, which is a blank image.
could you disable "send this image to geotagx" when the user is on geotagx?

**Comment by elliec** [comment]
@spMohanty the "page contains images that cant be detected" option doesn't seem to do anything

**Comment by elliec** [comment]
@spMohanty could you disable the reverse image search when people are not on geotagx? otherwise we could get lots of photos of the same thing

**Comment by spMohanty** [comment]
@elliec : maybe its a typo in one of your comments, but should i enable reverse search on geotagx or disable it ?

And thanks for pointing it out, the issue with internal links is a generic one and not specific to geotagx, i will handle it.

And the "page contains images that the extension cant detect" option sends the data to the server and it gets saved in the queue. It will appear on the admin dashboard for the sourcerers.

**Comment by elliec** [comment]
@spMohanty I think these have been addressed. I will close and open a new issue for anything that comes up in the published version of the extension
